[mypy]
python_version = 3.11
ignore_missing_imports = True        # ігнорувати сторонні бібліотеки без типів
follow_imports = silent             # не лізти у всі імпорти
disallow_untyped_defs = False       # не вимагати типи у всіх функціях
check_untyped_defs = False          # не перевіряти неанотовані функції
warn_unused_ignores = True          # попередження про невикористані # type: ignore
strict_optional = True               # строгий None-check
